"""add user_id to sales

Revision ID: e4e6ac394219
Revises: d9de88677504
Create Date: 2026-04-19 15:20:49.509432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4e6ac394219'
down_revision = 'd9de88677504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column as nullable first to handle existing data
    op.add_column('sales', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_sales_user_id', 'sales', 'users', ['user_id'], ['id'])
    # Update existing sales to have a default user (first admin/owner user if exists)
    op.execute('UPDATE sales SET user_id = 1 WHERE user_id IS NULL')
    # Now make it non-nullable
    op.alter_column('sales', 'user_id', existing_type=sa.Integer(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_sales_user_id', 'sales', type_='foreignkey')
    op.drop_column('sales', 'user_id')
    # ### end Alembic commands ###
